global:
  slack_api_url: https://hooks.slack.com/services/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

route:
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: 'montagu-monitor'
    username: 'montagu-bot'
    send_resolved: true
    title: "{{ .Status }}: {{ range .Alerts }}{{ .Annotations.summary }}, {{ end }}"
    text: "{{ range .Alerts }}* {{ .Annotations.description }}\n{{ end }}"
