version: '3'

services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "${PWD}/config/prometheus:/etc/prometheus"
      - prometheus-storage:/prometheus
    depends_on:
      - alertmanager
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
       # --web.enable-lifecycle enables reloading new config, see: https://prometheus.io/docs/operating/security/
       # all other flags are as in https://github.com/prometheus/prometheus/blob/master/Dockerfile

  alertmanager:
    image: prom/alertmanager
    restart: always
    volumes:
      - "${PWD}/config/alertmanager:/etc/alertmanager"
    ports:
      - "9093:9093"

  aws_metrics:
    build: aws_metrics
    restart: always
    volumes:
      - "${PWD}/aws_metrics/config/volume:/root/.aws"

  buildkite_metrics:
    image: reside/buildkite-agent-metrics
    restart: always
    env_file: config/buildkite.env
    command:
      - '-backend=prometheus'
      - '-interval=30s'

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini

  proxy:
    image: mrcide/monitor-proxy
    restart: unless-stopped
    volumes:
      - ./config/nginx/certificate.pem:/run/proxy/certificate.pem
      - ./config/nginx/key.pem:/run/proxy/key.pem
    ports:
      - '80:80'
      - '443:443'
    command: prometheus:9090 alertmanager:9093 grafana:3000 wpia-bots.dide.ic.ac.uk 80 443


volumes:
  grafana-storage: {}
  prometheus-storage: {}
