version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
    volumes:
    - prometheus_config:/etc/prometheus      
    depends_on: 
    - alertmanager
    network_mode: host

  alertmanager:
    image: prom/alertmanager
    ports:
    - "9093:9093"
    volumes:
    - prometheus_alertmanager_config:/etc/alertmanager

volumes:
  prometheus_config:
    external: true
  prometheus_alertmanager_config:
    external: true