version: '3'

services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "${PWD}/config/prometheus:/etc/prometheus"
    depends_on: 
      - alertmanager

  alertmanager:
    image: prom/alertmanager
    restart: always
    volumes:
      - "${PWD}/config/alertmanager:/etc/alertmanager"

  aws_metrics:
    build: aws_metrics
    restart: always
    volumes:
      - "${PWD}/aws_metrics/config/volume:/root/.aws"
