global:
  scrape_interval: 1s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

scrape_configs:
- job_name: 'demo'
  static_configs:
  - targets: ['localhost:5000']

rule_files:
  - alert-rules.yml