alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
- job_name: 'aws'
  static_configs:
  - targets: ['aws_metrics:80']

rule_files:
  - alert-rules.yml