groups:
- name: aws
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} is not responding"
  - alert: BackupBucketMissing
    expr: bucket_exists == 0
    annotations:
      summary: "Bucket {{ $labels.bucket_id }} does not exist"
      description: "Required S3 bucket {{ $labels.bucket_id }} does not exist"
  - alert: BackupStale
    expr: bucket_files_time_since_last_modified_hours > 24
    annotations:
      summary: "Backup to bucket {{ $labels.bucket_id }} is out of date"
      description: "More than 24 hours have passed since any files were modified in bucket {{ $labels.bucket_id }}"
  - alert: BackupShrinking
    expr: min(rate(bucket_files_total_size_mb[1h])) < 0
    annotations:
      summary: "Backup to bucket {{ $labels.bucket_id }} has decreased in size"
      description: "Over the last hour, the total amount of data stored in bucket {{ $labels.bucket_id }} has decreased"