groups:
  - name: aws
    rules:
      - alert: InstanceDown
        expr: up{job="aws"} == 0
        for: 5m
        annotations:
          error: "{{ $labels.instance }} is down"
      - alert: BackupBucketMissing
        expr: bucket_exists == 0
        annotations:
          error: "Required S3 bucket {{ $labels.bucket_id }} does not exist"
      - alert: BackupStale
        expr: bucket_files_time_since_last_modified_hours > 26
        annotations:
          error: "More than 26 hours have passed since any files were modified in bucket {{ $labels.bucket_id }}"

  - name: barman-shared
    rules:
      - alert: BarmanCacheStale
        expr: cache_out_of_date == 1
        annotations:
          error: "Barman cached metrics are out of date on {{ $labels.instance }}"
      - alert: BarmanNotRunning
        expr: barman_running == 0
        annotations:
          error: "Barman on {{ $labels.instance }} is not running"
      - alert: BarmanCheckFailed
        expr: barman_ok == 0
        annotations:
          error: "Barman check on {{ $labels.instance }} failed"
      - alert: BarmanMetricsDown
        expr: metrics_responding == 0
        annotations:
          error: "Barman metrics on {{ $labels.instance }} are not responding"

  - name: barman
    rules:
      - alert: BarmanDown
        expr: up{job="barman"} == 0
        for: 5m
        annotations:
          error: "{{ $labels.instance }} is down"

  - name: proxy
    rules:
      - alert: ProxyDown
        labels:
          frequency: "high"
        expr: up{job="proxy-metrics"} == 0
        for: 5m
        annotations:
          error: "Montagu on {{ $labels.instance }} is down"

  - name: barman-remote
    rules:
      - alert: NoRemoteBarman
        expr: max(up{job="barman-remote"}) == 0 or absent({job="barman-remote"}) == 1
        for: 5m
        annotations:
          error: "No EC2 barman instances are reporting metrics"

  - name: bb8
    rules:
      - alert: bb8Down
        expr: up{job="bb8"} == 0
        for: 5m
        annotations:
          error: "bb8 metrics is down"
      - alert: StaleBackup
        expr: time_since_last_backup_hours > 26
        annotations:
          error: "More than 26 hours have passed since bb8 backup of {{ $labels.target_id }}"
      - alert: MetadataCorrupted
        expr: metadata_present == 0
        annotations:
          error: "bb8 metadata missing for {{ $labels.target_id }}"
      - alert: TargetsShrunk
        expr: delta(number_of_targets[1h]) < 0
        annotations:
          error: "Number of targets backed up to Starport has shrunk in the last hour"

