global:
  slack_api_url: https://slack.com/api/chat.postMessage

route:
  receiver: 'slack'
  repeat_interval: 4m
  routes:
    - match:
        frequency: high
      repeat_interval: 20m
      receiver: 'slack'

templates:
  - 'templates/*.tmpl'

receivers:
  - name: 'slack'
    slack_configs:
      - channel: ${slack_channel}
        username: '{{ if eq .Status "firing" }}prometheus-sad-bot{{ else }}prometheus-happy-bot{{ end }}'
        send_resolved: true
        color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
        title: '{{ if eq .Status "firing" }}Problems detected{{ else }}Resolved{{ end }}'
        text: '{{ template "slack-alert-text" .}}'
        title_link: null
        icon_emoji: '{{ if eq .Status "firing" }}:lightning:{{ else }}:sun_with_face:{{ end }}'
        http_config:
          authorization:
            type: Bearer
            credentials: ${slack_oauth_token}

inhibit_rules:
  - source_matchers:
      - alertname = NoRemoteBarman
    target_matchers:
      - job = barman-remote
  - source_matchers:
      - alertname = BarmanDown
    target_matchers:
    equal:
    - instance
