global:
  slack_api_url: https://hooks.slack.com/services/${slack_webhook}

route:
  receiver: 'slack'

templates:
  - '../templates/*.tmpl'

receivers:
- name: 'slack'
  slack_configs:
  - channel: 'montagu-monitor'
    username: '{{ if eq .Status "firing" }}prometheus-sad-bot{{ else }}prometheus-happy-bot{{ end }}'
    send_resolved: true
    color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
    title: '{{ if eq .Status "firing" }}Problems detected{{ else }}Resolved{{ end }}'
    text: '{{ template "slack-alert-text" .}}'
    title_link: null
    icon_emoji: '{{ if eq .Status "firing" }}:lightning:{{ else }}:sun_with_face:{{ end }}'

