alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'aws'
    static_configs:
      - targets: ['aws_metrics:80']
  - job_name: 'barman'
    static_configs:
      - targets: ['annex.montagu.dide.ic.ac.uk:5000']
  - job_name: 'barman-remote'
    scrape_timeout: 60s
    scrape_interval: 2m
    ec2_sd_configs:
      - region: 'eu-west-2'
        access_key: ${aws_access_key_id}
        secret_key: ${aws_secret_key}
    relabel_configs:
      - source_labels: [__meta_ec2_public_dns_name]
        target_label: __address__
        regex: (.+)
        replacement: <%text>$</%text>{1}:5000

rule_files:
  - alert-rules.yml