alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:

  - job_name: 'proxy-metrics'
    static_configs:
      - targets: ['montagu.vaccineimpact.org:9113', 'support.montagu.dide.ic.ac.uk:9113', 'support.montagu.dide.ic.ac.uk:9114']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: (support)(.+)(9113)
        replacement: 'UAT'
      - source_labels: [__address__]
        target_label: instance
        regex: (.+)(9114)
        replacement: 'Science'
      - source_labels: [__address__]
        target_label: instance
        regex: (.+)(vaccineimpact)(.+)
        replacement: 'Production'

  - job_name: 'orderly-web'
    metrics_path: /reports/metrics
    scheme: https
    static_configs:
      - targets: ['montagu.vaccineimpact.org', 'support.montagu.dide.ic.ac.uk:10443', 'support.montagu.dide.ic.ac.uk:11443']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: (.+)(10443)
        replacement: 'UAT'
      - source_labels: [__address__]
        target_label: instance
        regex: (.+)(11443)
        replacement: 'Science'
      - source_labels: [__address__]
        target_label: instance
        regex: (.+)(vaccineimpact)(.+)
        replacement: 'Production'

  - job_name: 'aws'
    static_configs:
      - targets: ['aws_metrics:80']

  - job_name: 'bb8'
    static_configs:
      - targets: ['annex.montagu.dide.ic.ac.uk:5001']

  - job_name: 'barman'
    static_configs:
      - targets: ['annex.montagu.dide.ic.ac.uk:5000']

  - job_name: 'barman-remote'
    scrape_timeout: 60s
    scrape_interval: 2m
    ec2_sd_configs: &ec2
      - region: 'eu-west-2'
        access_key: ${aws_access_key_id}
        secret_key: ${aws_secret_key}
    relabel_configs:
      - source_labels: [__meta_ec2_public_dns_name]
        target_label: __address__
        regex: (.+)
        replacement: <%text>$</%text>{1}:5000

  - job_name: 'ec2-machine-metrics'
    ec2_sd_configs: *ec2
    relabel_configs:
      - source_labels: [__meta_ec2_public_dns_name]
        target_label: __address__
        regex: (.+)
        replacement: <%text>$</%text>{1}:9100

rule_files:
  - alert-rules.yml